### PR TITLE
Ft signup 158421249

### PR DESCRIPTION
**Pull request by benlegendj**
This PR creates sign up and forms where users can sign up by inputting their details.
**Description of Task to be completed:
**
Sign up form with four fields for inputs
-Username
-Email
-Password
-Confirm password

How to manually test this webpage

Clone this repository
After cloning, Navigate to Ride-My-Way
navigate further in the UI directory and open the signup.html

asdf

### CODE REVIEW

**Comment by meshack-mbuvi** [comment]
The design looks good.However , make sure the length of your **submit** button aligns well with other input fields. Also check whether you can improve the background color of submit button.

**Comment by LarryKarani** [comment]
awesome design bro, good color combo

**Comment by benlegendj** [comment]
thanks for your input. i will work on that

**Comment by Xerrex** [comment]
You surely know your css...
This [This cheat sheet](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) will help with mardown editing.

**Comment by evamaina** [comment]
Nice one

**Pull request merged**
